import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { field as Field } from '@code-ui/docstring';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Field name="" />
      </Head>
    </div>
  );
}
