import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { CodeLikeView } from '@code-ui/docstring';
import { IField } from '@code-ui/docstring/lib/field/type';
export default function Home() {
  const lang = 'jsx';

  const lang_field: IField = {
    tag: '@',
    name: 'lang',
    template: `{{ tag }}{{ name }} {{ option }}`,
    options: [
      {
        name: 'javascript',
        value: 'lang.javascript',
        description: 'javascript',
      },
      {
        name: 'dart',
        value: 'lang.dart',
        description: 'dart',
      },
    ],
  };

  const platform_field: IField = {
    tag: '@',
    name: 'platform',
    template: `{{ tag }}{{ name }} {{ options }} (juice.${lang})`,
    options: [
      {
        name: 'React',
        value: 'platform.react',
        description: 'tsx',
      },
      {
        name: 'Flutter',
        value: 'platform.flutter',
        description: 'flutter',
      },
    ],
  };

  function handleClick(field: string, value: string) {
    console.log(field);
    console.log(value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <CodeLikeView
          lang="dart" // defaults to js - "js" | "dart" | "paython" | LanguageConfig
          theme={'monokai'} // default style = monokai
          padding={'10px'}
          controls={[platform_field, lang_field]}
          expandableConfig={{
            lines: 2,
            expandable: true,
            hidable: true,
          }}
          onChange={handleClick}
        />
      </body>
    </div>
  );
}
