import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Docstring } from '@code-ui/docstring';
import { Interface } from '@code-ui/interface';
import React from 'react';
import {
  docstring_lang_field,
  docstring_platform_field,
  interfaceAttr1,
  interfaceAttr2,
} from '../example/example_fields';
import { BasedToken } from '@code-ui/token';

export default function Home() {
  function handleClick(field: string, value: string) {
    console.log(field);
    console.log(value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <BasedToken
          onClick={() => {
            console.log('onClicked');
          }}
          onDoubleClick={() => {
            console.log('onDoubleClick');
          }}
          onHover={true}
          hoverOverlayColor={'#9DB3FF'}
          cornerRadius={2}
          contentPadding={2}
          contentColor="#D7D7D7"
          backgroundColor="#3A3842"
          content={<span>hi</span>}
        />
        <Interface
          lang={'js'}
          theme={'monokai'}
          onChange={handleClick}
          interfaceName={'Props'}
          attrs={[interfaceAttr1, interfaceAttr2]}
        />

        <Docstring
          lang="dart" // defaults to js - "js" | "dart" | "paython" | LanguageConfig
          theme={'monokai'} // default style = monokai
          padding={'10px'}
          controls={[docstring_platform_field, docstring_lang_field]}
          expandableConfig={{
            lines: 2,
            expandable: true,
            hidable: true,
          }}
          onChange={handleClick}
        />
      </body>
    </div>
  );
}
